function [absoluteError, relativeError] = calculate1DSolvingError(p, U)
funA=@(X)( p.M_space * X * p.Q_time' ...
    + p.A_space' * X * p.D_time' ...
    + p.A_space * X * p.D_time ...
    + p.Q_space * X * p.M_time');

% TODO: funB only works if space ref = time ref
funB=@(x) reshape(funA(reshape(x, [sqrt(length(x)), ...
    sqrt(length(x))])), [length(x) 1]);

absoluteError = norm(funB(U) ...
    - reshape(p.rhs, [numel(p.rhs), 1]));
relativeError = absoluteError ...
    / norm(reshape(p.rhs, [numel(p.rhs), 1]));
end

